### ISSUE TITLE
Establish team lead compensation request review process

### ISSUE THREAD

**Issue by cbeams** [bisq-network/admin#28]
_@bisq-network/team-leads and @bisq-network/compensation-maintainers, please read and respond to this asap, as it deals with the orderly processing of Cycle 10 compensation requests, thanks._

## Criteria for delivery

- [ ] All Cycle 10 compensation requests submitted by the Monday Feb 10th deadline have been reviewed by their respective team leads
- [ ] Review feedback has been acknowledged and applied by each contributor
- [ ] The [Current Cycle Compensation Requests](https://github.com/bisq-network/compensation/projects/1?fullscreen=true) board has been used to facilitate the review process
- [ ] The process is documented on the wiki and ready to go for Cycle 11

## Tasks

- [x] @m52go to ask all contributors to submit their compensation request GitHub issues one week prior to the end of the proposal phase in order to allow for team lead review and subsequent adjustments prior to submitting the proposal via the DAO (#9)
- [x] @cbeams to put together Current Cycle Compensation Requests board
- [x] @cbeams to assign compensation requests to team leads as appropriate
- [x] @cbeams to write up proposed review process (see below)
- [ ] @bisq-network/team-leads to review proposed process and provide feedback
  - [ ] @m52go 
  - [ ] @ripcurlx 
  - [ ] @wiz 
  - [ ] @leo816 (with an eye toward taking over this aspect of the support team lead role)
- [ ] @bisq-network/compensation-maintainers to review proposed process and provide feedback
  - [ ] @MwithM 
- [ ] @bisq-network/team-leads to review their respective team members' compensation requests per the process
- [ ] Contributors to submit proposals to dao per the process
- [ ] @bisq-network/team-leads to transition issues to `Proposal Submitted` as each proposal is submitted
- [ ] @bisq-network/compensation-maintainers to close compensation requests with appropriate labels when voting is complete
- [ ] Document this process on the wiki (possibly in conjunction with migrating the existing compensation documentation at docs.bisq.network to the wiki)

### Submit compensation request GitHub issues
Contributors who wish to request compensation for the current cycle should submit a compensation request GitHub issue no later than 1 week prior to the end of the current cycle proposal phase.

WIP (Work in Progress) compensation requests may be submitted with a `[WIP] ` prefix in the title, e.g. `[WIP] For Cycle 10`.

When a contributor removes the `[WIP]` prefix from a compensation request issue, they should also add a comment stating `This issue is ready for team lead review`.

### Add new compensation requests to the Compensation Requests board
@bisq-network/compensation-maintainers should be watching the bisq-network/compensation repository, and upon being notified of a new compensation request issue, should add the issue as to the [Compensation Requests board](https://github.com/bisq-network/compensation/projects/1), putting `[WIP]` requests in the `In Progress` column, and putting non-WIP requests in the `Waiting for Team Lead Review` column.

When a compensation request issue is transitioned to the `Waiting for Team Lead Review` column, @bisq-network/compensation-maintainers should also assign the appropriate team lead(s) to that issue. The compensation maintainer must actually look at the content of the request and determine which team lead or leads are responsible. A given compensation request may include dev and growth work, for example, and so both @ripcurlx and @m52go should be assigned to review. When in doubt, the compensation maintainer should simply post a comment in the compensation request issue asking which team leads are appropriate.

### Team Lead Review

When a team lead is assigned to a compensation request issue, they should propmtly review it with regard to whether the work meets the definition of delivered, and whether it fits within the team budget. The team lead should add feedback and comments as a appropriate, and assign the contributor to the issue to indicate that they are expected to respond to the review.

When the review process is complete, i.e. all team lead feedback has been addressed, the team lead should transition the issue to the `Reviewed by Team Lead` column.

### Submit compensation request DAO proposal
Once a compensation request has been transitioned to the `Reviewed by Team Lead` column, the contributor is free to submit their request as a DAO proposal per the usual process. When complete, the contributor should add a comment that reads `DAO proposal transaction ID: <txid>`.

When @bisq-network/compensation-maintainers or @bisq-network/team-leads see the `DAO proposal transaction ID` comment, they should transition the issue to the `Proposal Submitted` column.

### Closing compensation requests after voting

Per the usual process, when the vote reveal phase is complete, @bisq-network/compensation-maintainers should close each proposal in the `Proposal Submitted` column appropriately, indicating via comment and label whether the request `was:approved` or `was:rejected`.
When a team lead is assigned 

### Notes

When the above process has been completed, the Compensation Requests board should be empty save for any new `[WIP]` compensation requests for future cycles that may have come in during the process.

The process above assumes prompt action from both @bisq-network/compensation-maintainers and @bisq-network/team-leads with regard to responding to issue state changes, transitioning issues on the board appropriately, etc. If anyone has doubts about their ability to do this in a timely fashion (same-day), please speak up.

**Comment by cbeams** [comment]
Note that the first two sections of the process:

1. Submit compensation request GitHub issues
2. Add new compensation requests to the Compensation Requests board

have **already been completed** for Cycle 10. What's needed to complete the process for Cycle 10 are the remaining three sections:

3. Team lead review
4. Submit compensation request DAO proposals
5. Close compensation requests after voting

**Comment by m52go** [comment]
This seems reasonable to me, but I don't understand the role of the project board. Could we achieve the purpose of the board with issue tags (i.e., in-progress, awaiting-review, etc)?

**Comment by cbeams** [comment]
The board is for better visual management and to make the process/workflow quite explicit. This reminds me to give team-leads write access to the compensation repository so that we can all transition the issues as discussed. I would say let's try it with the board this time around, and if it seems like overkill we consider dropping it in a later cycle.

**Comment by cbeams** [comment]
@bisq-network/team-leads and @bisq-network/compensation-maintainers, please check the box next to your name in the description comment when you've reviewed this and provided feedback (if any).

**Comment by wiz** [comment]
Great process. However, maybe we need to be more clear on who is approving/reviewing which line items in the compensation request. It would be cleaner to only submit one compensation request per team but that might be too much paperwork.

**Comment by wiz** [comment]
Also, for best practices please require contributors to post TXID of their DAO proposal as the final step in the process, to discourage impersonation scams. Remember, several of us have previously been impersonated in slack, email, etc.
<img width="434" alt="Screen Shot 2020-02-10 at 23 14 44" src="https://user-images.githubusercontent.com/232186/74205301-249b3180-4cba-11ea-9f5f-039bce50dd08.png">

**Comment by m52go** [comment]
@cbeams which team lead is reviewing compensation requests for support? Is it you?

**Comment by MwithM** [comment]
If there's disagreement on a rejected request, where should discussion occur? Here or Keybase #compensation channel? I was leaving rejected requests open for a week or so for discussion.
I suppose that rejected compensation requests will be very rare, as they will be already reviewed by team leaders, meaning it's a delivered task, but just in case.

**Comment by leo816** [comment]
Great process, this seems fair to me.

**Comment by cbeams** [comment]
@wiz wrote:
> for best practices please require contributors to post TXID of their DAO proposal as the final step in the process

From the `Submit compensation request DAO proposals` section:

> When complete, the contributor should add a comment that reads `DAO proposal transaction ID: <txid>`.

@m52go wrote:
> @cbeams which team lead is reviewing compensation requests for support? Is it you?

Yes, me, with the goal that @leo816 takes over in a subsequent cycle. My assignments on the board should already reflect this.

@leo816 wrote:
> Great process, this seems fair to me.

Great. I've checked the box next to your name on your behalf.

@MwithM wrote:
> If there's disagreement on a rejected request, where should discussion occur? [...] I was leaving rejected requests open for a week or so for discussion.

Comments / discussion can continue on an issue even after it is closed. I'd say it makes sense to close it immediately on vote reveal as `was:approved` or `was:rejected`, as nothing is going to change that fact, but people are free to continue conversation about it on the original issue. Seems like the most appropriate and in-context place to do it in any case.

**Comment by cbeams** [comment]
@bisq-network/team-leads, I just made the following change:

<img width="644" alt="image" src="https://user-images.githubusercontent.com/301810/74261022-d22e3500-4cfa-11ea-93e4-90d4b8dd4e2d.png">

You can see an example of how @wiz did this at https://github.com/bisq-network/compensation/issues/481#issuecomment-584460260. It's important to add a comment to this effect, because otherwise the contributor won't get any signal that the review is in fact complete, which would likely lead to a delay in getting their DAO proposal submitted.

Note that I do NOT think it's important that we actually assign the issue to the contributor (as @wiz mentioned, but did not actually do, in his comment). Contributors know that the issue is theirs to manage through to completion and they don't need assignment metadata to make that clear. @wiz, you removed yourself as assignee when you transitioned the issue to `Reviewed by Team Lead`, and I think it's probably best to leave yourself assigned. It generally helps everyone know who was responsible for the review, and it also leaves that metadata in place for when you're doing GH Issues queries to figure out what all you did today / last cycle / etc.

**Comment by cbeams** [comment]
Heads up, I just renamed `Waiting for Team Lead Review` to `In Review` and renamed `Reviewed by Team Lead` to `Review Complete`.

The reason for the change to `In Review` is that issues in this column aren't always strictly waiting for the team lead. They may be waiting for the contributor to respond to team lead feedback. In any case, all such issues are "in review" until they're transitioned to `Review Complete`. See my latest edit diff in the description for details.
