### ISSUE TITLE
Create roles for each team lead

### ISSUE THREAD

**Issue by cbeams** [bisq-network/admin#31]
It's too late to do this for Cycle 10, but we should get it done for Cycle 11.

- [x] Admin Team Lead https://github.com/bisq-network/roles/issues/98
- [x] Dev Team Lead https://github.com/bisq-network/roles/issues/99
- [x] Growth Team Lead https://github.com/bisq-network/roles/issues/99
- [x] Ops Team Lead https://github.com/bisq-network/roles/issues/100
- [x] Support Team Lead https://github.com/bisq-network/roles/issues/101

**Comment by cbeams** [comment]
Closing as complete. See linked issues in description. @bisq-network/team-leads, please post cycle reports for these roles as you see fit. We can figure out over time what a good format looks like there. We haven't been claiming compensation for these roles, but assuming we begin to, it'll be all the more important that they are handled in a 1st-class way like all other roles.
