### ISSUE TITLE
 2020-02-27 @team-leads call

### ISSUE THREAD

**Issue by cbeams** [bisq-network/admin#58]
Previous call: #34

## Agenda

- [x] What do we need to do to consider rolling out the budget (bisq-network/projects#2) complete?
- [x] Project management (bisq-network/projects#1) update / questions
  - [x] schedule bi-weekly project review meetings in this same time slot and starting doing team lead meetings bi-weekly as well?
  - [x] proposed metrics projects
  - [x] Bitcoin2020 project (bisq-network/projects#14)
  - [x] growth project(s) around liquidity
- [x] Support check-in
  - [x] Can we call https://github.com/bisq-network/projects/issues/4 delivered?

## Action items
 - [ ] @ripcurlx to adapt his budget spreadsheet to accommodate all teams' per-cycle budgets vs actuals as a ledger where the totals roll over cycle to cycle (#59)
 - [x] @ripcurlx and @cbeams to meet with freimair, craft overall Tor v3 upgrade project plan (scheduled)
 - [ ] @m52go to add Criteria for Delivery and Measures of Success sections to Bitcoin 2020 project and add link to kanban board where detailed tasks for the project are being managed
 - [ ] @cbeams to close bisq-network/projects#4
 - [x] @cbeams to schedule first project review meeting for this time next week
 - [ ] @cbeams to announce first project review meeting (#47)

**Comment by cbeams** [comment]
@bisq-network/team-leads, please add any agenda items you have as comments, thanks.

**Comment by cbeams** [comment]
Task issues for action items in the description have been created and referenced where appropriate. Please check the boxes on your stuff as you complete it.
