### ISSUE TITLE
Document the Refund Agent role

### ISSUE THREAD

**Issue by cbeams** [bisq-network/admin#69]
This role has been in effect for some time now, but has not properly been documented and managed until now.

- [x] @RefundAgent to create role issue at bisq-network/roles#93
- [x] @RefundAgent to post Cycle 11 update (https://github.com/bisq-network/roles/issues/93#issuecomment-593149104)
- [x] @cbeams to create @bisq-network/refund-agents team
- [x] @cbeams to invite @RefundAgent to join bisq-network GitHub org
  - [ ] ~~@RefundAgent to accept~~
- [x] @cbeams to assign @RefundAgent to bisq-network/roles#93
- [x] @cbeams to create stub role documentation at https://bisq.wiki/Refund_Agent
- [x] @cbeams to update description of bisq-network/roles#93 accordingly
- [x] @RefundAgent to flesh out role documentation at https://bisq.wiki/Refund_Agent
  - [x] @cbeams to review

**Comment by cbeams** [comment]
@RefundAgent, per the task list in the description above, please complete the Description, Duties, Rights and Bonding sections of https://bisq.wiki/Refund_Agent to the best of your ability and leave a comment here saying you've done so. Thanks.

**Comment by RefundAgent** [comment]
I have now written somewhat terse texts for  https://bisq.wiki/Refund_Agent
I was not aware that this should be written before.

**Comment by cbeams** [comment]
Closing as complete. See https://github.com/bisq-network/admin/issues/70#issuecomment-607890856.
